apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog-items-deployment
spec:
  selector:
    matchLabels:
      app: catalog-items
  template:
    metadata:
      labels:
        app: catalog-items
    spec:
      containers:
        - name: catalog-items
          image: mattavireddy/catalogitems:v1
          resources:
            limits:
              memory: "720Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-items-service
spec:
  type: LoadBalancer
  selector:
    app: catalog-items
  ports:
    - port: 3000
      targetPort: 3000
